jobs:
  license_check:
    runs-on: ubuntu-lastest
    steps:
      - name: Check license-checker CSV file without headers
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          external: "npm-license-checker.csv"
          external-format: "csv"
          external-options: "{:skip-header true}"
          fail: "StrongCopyleft,NetworkCopyleft,Other,Error"
          fails-only: true
          exclude: "DiamondLightSource.*"
          exclude-license: "(?i)copyright"
          totals: true
          verbose: 1
          github-token: ${{ secrets.OAUTH_TOKEN_GITHUB }}
